on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.AARONMOREYCOM_CONTENT_PAT }}

      - name: Checkout main on all submodules
        run: |
          # Do it all in one shot
          git submodule update --init --recursive --remote
          # git switch main
          # git pull

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build
