on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.AARONMOREYCOM_CONTENT_PAT }}

      - name: Checkout main on all submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
          cd aaronmoreycom_content
          git switch astro-conversion

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy public --project-name=dotcom_astro
